# database generated on 2023-08-09 07:14 GMT
!!omap
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - add
