# database generated on 2023-08-09 06:19 GMT
!!omap
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - add
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/addi-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - addi
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/and-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - and
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/andi-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - andi
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/auipc-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - auipc
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/beq-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - beq
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bge-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bge
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bgeu-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bgeu
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/blt-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - blt
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bltu-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bltu
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bne-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - bne
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/fence-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fence
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jal-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - jal
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jalr-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - jalr
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lb-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lb-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lbu-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lbu-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lh-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lh-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lhu-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lhu-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lui-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lui
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lw-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - lw-align
- ? /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/misalign1-jalr-01.S
  : commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - misalign1-jalr
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/or-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - or
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/ori-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - ori
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sb-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sb-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sh-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sh-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sll-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sll
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slli-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slli
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slt-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slt
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slti-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - slti
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltiu-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sltiu
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltu-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sltu
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sra-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sra
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srai-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srai
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srl-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srl
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srli-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - srli
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sub-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sub
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sw-align-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - sw-align
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xor-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - xor
- /home/abdul_waheed/github_files/UET-Pcore-with-c-ext/verif/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xori-01.S:
    commit_id: '-'
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - xori
